{
    'name': 'TTM Admin Panel',
    'version': '19.0.2.0.0',
    'category': 'Administration',
    'author': 'IB Teguh TM',
    'summary': 'Manage Odoo tenants: create new databases and subdomains automatically',
    'depends': ['base', 'web'],
    'data': [
        'security/ir_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'data/ir_config_parameter.xml',
        'views/ttm_tenant_group_views.xml',
        'views/ttm_user_tenant_views.xml',
        'views/ttm_tenant_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
